(in-package :fern)

(defstruct (apu (:conc-name nil)))

(defun read-apu/pulse-1-control (apu) (TODO))
(defun read-apu/pulse-1-ramp-control (apu) (TODO))
(defun read-apu/pulse-1-fine-tune (apu) (TODO))
(defun read-apu/pulse-1-coarse-tune (apu) (TODO))
(defun read-apu/pulse-2-control (apu) (TODO))
(defun read-apu/pulse-2-ramp-control (apu) (TODO))
(defun read-apu/pulse-2-fine-tune (apu) (TODO))
(defun read-apu/pulse-2-coarse-tune (apu) (TODO))
(defun read-apu/triangle-control-1 (apu) (TODO))
(defun read-apu/triangle-control-2 (apu) (TODO))
(defun read-apu/triangle-frequency-1 (apu) (TODO))
(defun read-apu/triangle-frequency-2 (apu) (TODO))
(defun read-apu/noise-control (apu) (TODO))
(defun read-apu/noise-frequency-2 (apu) (TODO))
(defun read-apu/delta-modulation-control (apu) (TODO))
(defun read-apu/delta-modulation-d/a (apu) (TODO))
(defun read-apu/delta-modulation-address (apu) (TODO))
(defun read-apu/delta-modulation-data-length (apu) (TODO))
(defun read-apu/sound-channels (apu) (TODO))

(defun write-apu/pulse-1-control (apu value) (TODO))
(defun write-apu/pulse-1-ramp-control (apu value) (TODO))
(defun write-apu/pulse-1-fine-tune (apu value) (TODO))
(defun write-apu/pulse-1-coarse-tune (apu value) (TODO))
(defun write-apu/pulse-2-control (apu value) (TODO))
(defun write-apu/pulse-2-ramp-control (apu value) (TODO))
(defun write-apu/pulse-2-fine-tune (apu value) (TODO))
(defun write-apu/pulse-2-coarse-tune (apu value) (TODO))
(defun write-apu/triangle-control-1 (apu value) (TODO))
(defun write-apu/triangle-control-2 (apu value) (TODO))
(defun write-apu/triangle-frequency-1 (apu value) (TODO))
(defun write-apu/triangle-frequency-2 (apu value) (TODO))
(defun write-apu/noise-control (apu value) (TODO))
(defun write-apu/noise-frequency-2 (apu value) (TODO))
(defun write-apu/delta-modulation-control (apu value) (TODO))
(defun write-apu/delta-modulation-d/a (apu value) (TODO))
(defun write-apu/delta-modulation-address (apu value) (TODO))
(defun write-apu/delta-modulation-data-length (apu value) (TODO))
(defun write-apu/sound-channels (apu value) (TODO))
